### ISSUE TITLE
Issue with Unity Visual Scripting

### ISSUE THREAD

**Issue by ron77950** [arimger/Unity-Editor-Toolbox#123]
When I try to make a build in Unity 2022.3 I get this error with Unity Visual Scripting. These files are generated by clicking Generate in Project Settings > Visual Scripting > Custom Inspector Properties.

`Assets\Unity.VisualScripting.Generated\VisualScripting.Core\Property Providers\PropertyProvider_Toolbox_Editor_Folders_FolderData.cs(16,125): error CS0234: The type or namespace name 'Editor' does not exist in the namespace 'Toolbox' (are you missing an assembly reference?)`

**Comment by arimger** [comment]
Hi, I reviewed the issue, and it appears to be a regression on Unity's site. The `FolderData PropertyProvider` should be generated in the Editor directory and excluded during builds. As a temporary fix, I can move it to the runtime assembly since it shouldn't impact the package.

**Comment by arimger** [comment]
Changed in https://github.com/arimger/Unity-Editor-Toolbox/pull/127.
